name: Daily update with new data

on:
  schedule:
    - cron: '45 12 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t washtimer:latest

      - name: Load new price data
        run: docker run -v $PWD:/app washtimer:latest -c "python load_prices.py"

      - name: Update README with new data
        run: docker run -v $PWD:/app washtimer:latest -c "python main.py"

      - uses: scapeville/action-git-add-all-then-commit-then-push@v1
        with:
          name: gh   # (optional)
          email: action  # (optional)
          msg: daily update    # (optional)
        env:
          GH_TOKEN: ${{ github.UPDATE_KEY }}
